#!/bin/bash
# Script to help create Istio dashboard visualizations
# This provides the ES|QL queries that can be used in Kibana

ELASTIC_ENDPOINT="${ELASTIC_ENDPOINT:-https://otel-demo-a5630c.kb.us-east-1.aws.elastic.cloud}"
ELASTIC_API_KEY="${ELASTIC_API_KEY:-X3JMeTZKa0JqTzZCYWgtaGY5YzI6X3UwY01hZ0tXaEplRExkVHoxeE1XQQ==}"

echo "=========================================="
echo "Istio Dashboard Visualization Queries"
echo "=========================================="
echo ""
echo "Use these ES|QL queries in Kibana Discover or Lens to create visualizations:"
echo ""
echo "1. REQUEST RATE:"
echo "FROM metrics-apm.app.istio_gateways-default"
echo "| WHERE @timestamp > NOW() - 1 hour AND envoy_cluster_upstream_rq_total IS NOT NULL"
echo "| STATS total_requests = SUM(envoy_cluster_upstream_rq_total) BY @timestamp"
echo "| SORT @timestamp ASC"
echo ""
echo "2. ACTIVE CONNECTIONS:"
echo "FROM metrics-apm.app.istio_gateways-default"
echo "| WHERE @timestamp > NOW() - 1 hour AND envoy_cluster_upstream_cx_active IS NOT NULL"
echo "| STATS active = MAX(envoy_cluster_upstream_cx_active) BY @timestamp"
echo "| SORT @timestamp ASC"
echo ""
echo "3. CLUSTER HEALTH:"
echo "FROM metrics-apm.app.istio_gateways-default"
echo "| WHERE @timestamp > NOW() - 1 hour"
echo "| STATS healthy = SUM(COALESCE(envoy_cluster_membership_healthy, 0)),"
echo "        total = SUM(COALESCE(envoy_cluster_membership_total, 0))"
echo "| EVAL health_pct = (healthy / total) * 100"
echo ""
echo "4. ERROR RATE:"
echo "FROM metrics-apm.app.istio_gateways-default"
echo "| WHERE @timestamp > NOW() - 1 hour"
echo "| STATS errors = SUM(COALESCE(envoy_cluster_upstream_rq_rx_reset, 0) +"
echo "                     COALESCE(envoy_cluster_upstream_rq_tx_reset, 0)) BY @timestamp"
echo "| SORT @timestamp ASC"
echo ""
echo "5. BYTES TRANSFERRED:"
echo "FROM metrics-apm.app.istio_gateways-default"
echo "| WHERE @timestamp > NOW() - 1 hour"
echo "| STATS bytes_rx = SUM(COALESCE(envoy_cluster_upstream_cx_rx_bytes_total, 0)),"
echo "        bytes_tx = SUM(COALESCE(envoy_cluster_upstream_cx_tx_bytes_total, 0))"
echo "  BY @timestamp"
echo "| SORT @timestamp ASC"
echo ""
echo "=========================================="
echo "Dashboard URL:"
echo "${ELASTIC_ENDPOINT}/app/dashboards"
echo "=========================================="
echo ""
echo "To create the dashboard:"
echo "1. Go to Analytics > Dashboards"
echo "2. Click 'Create dashboard'"
echo "3. Use the queries above to create visualizations"
echo "4. Add visualizations to the dashboard"
echo ""

